### ISSUE TITLE
Setup profile

### ISSUE THREAD

**Issue by narendraanjana09** [OfficialFindCoder/FindCoder-Reporting-Bugs#66]
In the 'write something about yourself section', It got stuck with 'special characters issue'. I had written nothing, it's just some commas and dots. But after removing them also it didn't work.

**Comment by arpan-pro-learner** [comment]
I  also have the same problem while setting up my profile
so I understand it as a bug and left my profile setup as it is  
please team look for this bug because it creates a bad experience for the user onboarding and profile setup 
I can also understand that this is version 1 of the website so bugs are expected
